#!/bin/bash

# ASCII Art
ascii_art="
    __  __          __           ____           __        ____         
   / / / /_  ______/ /________ _/  _/___  _____/ /_____ _/ / /__  _____
  / /_/ / / / / __  / ___/ __ `// // __ \/ ___/ __/ __ `/ / / _ \/ ___/
 / __  / /_/ / /_/ / /  / /_/ // // / / (__  ) /_/ /_/ / / /  __/ /    
/_/ /_/\__, /\__,_/_/   \__,_/___/_/ /_/____/\__/\__,_/_/_/\___/_/     
      /____/                                                           
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Function to display messages
echo_message() {
    echo -e "\033[1;32m$1\033[0m"
}

echo_message " Do you install skyport panel (yes/no)"
read answer

if [ "$answer" != "yes" ]; then
    echo_message "Installation aborted."
    exit 0
fi

echo_message "* Installing Dependencies"

# Update package list and install dependencies
sudo apt update
sudo apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs -y 
sudo apt install git -y

echo_message "* Installed Dependencies"

echo_message "* Installing Files"

# Create directory, clone repository, and install files
mkdir -p skyport
cd panel5 || { echo_message "Failed to change directory to skyport"; exit 1; }
git clone https://github.com/achul123/panel5
cd panel5 || { echo_message "Failed to change directory to panel"; exit 1; }
npm install

echo_message "* Installed Files"

echo_message "* Starting Skyport"

# Run setup scripts
npm run seed
npm run createUser

echo_message "* Starting Skyport BY JISHNU"

# Install panel and start the application
node .

echo_message "* Skyport Installed and Started on Port 3001"
