#!/bin/bash



# ASCII Art
ascii_art="

                       _ _     _                 
                      | (_)   | |                
                      | |_ ___| |__  _ __  _   _ 
                  _   | | / __| '_ \| '_ \| | | |
                 | |__| | \__ \ | | | | | | |_| |
                  \____/|_|___/_| |_|_| |_|\__,_|
                                                 
                                                 
                                  
"
}
  # panel
    panel() {
    sudo apt update
    sudo apt install -y nodejs git
    git clone https://github.com/achul123/panel5
    cd panel5
    npm install
    npm run seed
    npm run createUser
    node .
}
  # node
    node () {
    git clone https://github.com/achul123/skyportd
    cd skyportd
    npm install

}
 # Main Menu
echo -e "${CYAN}Select an option:${NC}"
echo -e "1. Install Panel "
echo -e "2. install Node "
echo -e "3. Exit"
read -p "Enter your choice (1-3): " choice

case $choice in
    1)
        panel
        ;;
    2)
        node
        ;;    
    3)
        echo -e "${GREEN}Exiting...${NC}"
        exit 0
        ;;
    *)
        echo -e "${RED}Invalid option. Please select 1 or 2.${NC}"
        exit 1
        ;;
esac    
